default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: development_assignment_1
  
test:
  <<: *default
  database: development_assignment_1

production:
  <<: *default
  url: postgresql://${{ postgres }}:${{ 6yFK62zhtaCnKdkYKO7x }}@${{ containers-us-west-127.railway.app }}:${{ 7483 }}/${{ railway }}
  database: development_assignment_1
  username: postgres
  password: 6yFK62zhtaCnKdkYKO7x